<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE Company [
	<!ELEMENT Company (name, email, phone, Prosthetics)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT email (#PCDATA)>
	<!ELEMENT phone (#PCDATA)>
	<!ELEMENT Prosthetics (prosthetics)>
	<!ATTLIST prosthetics code CDATA #REQUIRED>
	<!ELEMENT prosthetics (price, functionalities, type, model)>
	<!ELEMENT price (#PCDATA)>
	<!ELEMENT functionalities (#PCDATA)>
	<!ELEMENT type (#PCDATA)>
	<!ELEMENT model (#PCDATA)>
]>

<Company>
	<name>ExoHealth</name>
	<email>exohealth@health.com</email>
	<phone>910234567</phone>
	<Prosthetics>
		<prosthetics code="213">
			<price> 89.99 </price>
			<functionalities> Walk and jump </functionalities>
			<type> Right leg </type>
			<model> C980 </model>
		</prosthetics>
	</Prosthetics>
</Company>